[package]
name = "inventory"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ic-cdk = "0.6"
ic-cdk-macros = "0.6"

