[package]
name = "data_aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.11.3"
ic-cdk-macros = "0.8.1"
candid = { version = "0.9.9", features = ["parser"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.1"

[lib]
crate-type = ["cdylib"]
