[package]
name = "data_aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.6.10"
ic-cdk-macros = "0.6.10"
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
candid = "0.8"



[lib]
crate-type = ["cdylib"]
